name: Build QyzROM For S9180

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: Ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ dm3q ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: qlenlen/TIK_mine
          ref: master
          token: ${{ secrets.TOKEN }}
          path: qyz
          submodules: 'recursive'

      - name: Free disk space (1/2)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (2/2)
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r qyz/requirements.txt

      - name: Set up build environment
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl xxd patchelf flex lz4 cpio tar zip
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download firmware
        run: |
          git clone https://github.com/keklick1337/gnsf.git
          cd gnsf
          mkdir -p ../qyz/UI7
          pip install -r requirements.txt
          
          ROM_VERSION=$(./gnsf.py -m SM-S9180 -r CHC check)
          echo "ROM Version: $ROM_VERSION"
          echo "ROM_VERSION=$ROM_VERSION" >> $GITHUB_ENV
          
          ./gnsf.py -m SM-S9180 -r CHC check
          ./gnsf.py \
            -m SM-S9180 \
            -r CHC \
            -s R5CW139E77Z \
            download \
            -O ../qyz/UI7
          ls ../qyz/UI7
          cd ..

      - name: Build ROM
        env:
          RUN_EXTRA_STEPS: "1"
        run: |
          cd qyz
          export PYTHONPATH=$(pwd)
          python src/device/dm3q_chn.py

      - name: Upload to GoFile
        id: upload
        run: |
          ZIP_FILE=$(find qyz/UI7 -maxdepth 1 -type f -name "*.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found!"
            exit 1
          fi

          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          URL=$(echo "$RESPONSE" | jq -r '.data.downloadPage')
          echo "download_url=$URL" >> $GITHUB_OUTPUT

      - name: Create a new release with GoFile link
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          name: ${{ env.ROM_VERSION }}
          tag: "v${{ env.ROM_VERSION }}"
          body: |
            这是一个自动构建的ROM，适用于三星 Galaxy S9180（DM3Q）设备

            **下载链接**: ${{ steps.upload.outputs.download_url }}

            > WARNING! THESE BUILDS MAY NOT BOOTABLE, ONLY FLASH FOR TESTING PURPOSES ONLY IF THE DEVELOPER TOLD YOU.
