name: Build QyzROM for S23 Series

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - model: SM-S9110
            name: S23 (SM-S9110)
            serial: RFCW81DHWWP
          - model: SM-S9160
            name: S23+ (SM-S9160)
            serial: R5CW23450PZ
          - model: SM-S9180
            name: S23 Ultra (SM-S9180)
            serial: R5CW139E77Z

    outputs:
      device_name: ${{ matrix.device.name }}
      download_url: ${{ steps.upload.outputs.download_url }}
      rom_version: ${{ env.ROM_VERSION }}

    env:
      MODEL: ${{ matrix.device.model }}
      DEVICE_NAME: ${{ matrix.device.name }}
      DEVICE_SERIAL: ${{ matrix.device.serial }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: qlenlen/TIK_mine
          ref: master
          token: ${{ secrets.TOKEN }}
          path: qyz
          submodules: 'recursive'

      - name: Free disk space (1/2)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (2/2)
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r qyz/requirements.txt

      - name: Set up build environment
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl xxd patchelf flex lz4 cpio tar zip
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download firmware
        run: |
          git clone https://github.com/keklick1337/gnsf.git
          cd gnsf
          mkdir -p ../qyz/UI7
          pip install -r requirements.txt
          ROM_VERSION=$(./gnsf.py -m $MODEL -r CHC check | grep -oP 'Firmware:\s*\K\S+' | cut -d'/' -f1)
          echo "ROM Version: $ROM_VERSION"
          echo "ROM_VERSION=$ROM_VERSION" >> $GITHUB_ENV
          ./gnsf.py \
            -m $MODEL \
            -r CHC \
            -s $DEVICE_SERIAL \
            download \
            -O ../qyz/UI7
          ls ../qyz/UI7
          cd ..

      - name: Build ROM
        env:
          RUN_EXTRA_STEPS: "1"
        run: |
          cd qyz
          export PYTHONPATH=$(pwd)
          python src/device/dmXq_chn.py

      - name: Upload to GoFile
        id: upload
        run: |
          ZIP_FILE=$(find qyz/UI7 -maxdepth 1 -type f -name "*.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found!"
            exit 1
          fi
          NEW_ZIP_NAME="QyzROM_CHC_${{ env.ROM_VERSION }}_${{ env.MODEL }}.zip"
          mv "$ZIP_FILE" "qyz/UI7/$NEW_ZIP_NAME"
          RESPONSE=$(curl -s -F "file=@qyz/UI7/$NEW_ZIP_NAME" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" "https://upload-eu-par.gofile.io/uploadFile")
          URL=$(echo "$RESPONSE" | jq -r '.data.downloadPage')
          echo "download_url=$URL" >> $GITHUB_OUTPUT

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate release body
        run: |
          echo "这是一个自动构建的ROM，适用于 S23 系列以下机型：" > release_body.md
          echo "" >> release_body.md
          echo "**${{ needs.build.outputs.device_name[0] }}**" >> release_body.md
          echo "下载链接: ${{ needs.build.outputs.download_url[0] }}" >> release_body.md
          echo "" >> release_body.md
          echo "**${{ needs.build.outputs.device_name[1] }}**" >> release_body.md
          echo "下载链接: ${{ needs.build.outputs.download_url[1] }}" >> release_body.md
          echo "" >> release_body.md
          echo "**${{ needs.build.outputs.device_name[2] }}**" >> release_body.md
          echo "下载链接: ${{ needs.build.outputs.download_url[2] }}" >> release_body.md
          echo "" >> release_body.md
          echo "内核为 KernelSU LKM 需安装 官方apk 以激活 root 权限" >> release_body.md
          echo "" >> release_body.md
          echo "> WARNING! THESE BUILDS MAY NOT BOOTABLE, ONLY FLASH FOR TESTING PURPOSES ONLY IF THE DEVELOPER TOLD YOU." >> release_body.md

      - name: Create unified release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          name: "QyzROM_CHC_${{ needs.build.outputs.rom_version[0] }}"
          tag: ${{ needs.build.outputs.rom_version[0] }}
          bodyFile: release_body.md


